# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Example Pipar Sool'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["pipar_sool_dongle","pipar_sool_left","pipar_sool_right"]'
      alphas: 'dvorak'
      clipboard: 'mac'
